
Vagrant.configure("2") do |config|

  config.vm.define :test_vm do |test_vm|
    test_vm.vm.provider :kubevirt do |kubevirt|
      kubevirt.template = 'working'
      kubevirt.cpus = 1
      kubevirt.memory = 512
      # kubevirt.image = 'registry:5000/kubevirt/fedora-cloud-registry-disk-demo:devel'
      # kubevirt.pvc = 'test-disk'
    end
  end

  config.vm.provider :kubevirt do |kubevirt|
    kubevirt.hostname = '192.168.121.121'
    kubevirt.port = '8443'
    kubevirt.token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3N'
  end
end